server:
  port: 6688
spring:
  application:
    name: gateway
ptoj:
  redis:
    host: localhost
    port: 6379
    password: 123456
  nacos:
    host: localhost
    port: 8848
    username: nacos
    password: nacos
  sentinel:
    host: localhost
    port: 8858