server:
  port: 6688
spring:
  application:
    name: gateway
ptoj:
  redis:
    host: localhost
    port: 6379
    password: 123456
  nacos:
    host: localhost
    port: 8848
    username: nacos
    password: nacos
security:
  ignore:
    whitelist:
      - /admin/login
      - /check-username-or-email
      - /get-problem-detail
      - /get-problem-list
      - /get-random-problem
      - /get-all-problem-tags
      - /get-problem-tags-and-classification
      - /get-problem-tags
      - /language/**