spring:
  profiles:
    active: dev
  redis:
    host: ${ptoj.redis.host}
    port: ${ptoj.redis.port}
    timeout: 60000
    jedis:
      pool:
        min-idle: 10 #连接池中的最小空闲连接
        max-idle: 50 #连接池中的最大空闲连接
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
    password: ${ptoj.redis.password}
  cloud:
    nacos:
      server-addr: ${ptoj.nacos.host}:${ptoj.nacos.port}
      username: ${ptoj.nacos.username}
      password: ${ptoj.nacos.password}
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/admin/login,/admin/logout,/admin/user/**,/user/**,/file/generate-user-excel
        - id: problem
          uri: lb://problem-service
          predicates:
            - Path=/admin/problem/**
dubbo:
  application:
    name: dubbo-${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${ptoj.nacos.host}:${ptoj.nacos.port}?username=${ptoj.nacos.username}&password=${ptoj.nacos.password}
logging:
  level:
    love.pangteen: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"