server:
  port: 6688
spring:
  application:
    name: gateway
  profiles:
    active: dev
  redis:
    host: ${ptoj.redis.host}
    port: ${ptoj.redis.port}
    timeout: 60000
    jedis:
      pool:
        min-idle: 10 #连接池中的最小空闲连接
        max-idle: 50 #连接池中的最大空闲连接
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
    password: ${ptoj.redis.password}
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
    gateway:
      routes:
#        - id: item # 路由规则id，自定义，唯一
#          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
#          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
#            - Path=/items/**,/search/** # 这里是以请求路径作为判断规则
#        - id: cart
#          uri: lb://cart-service
#          predicates:
#            - Path=/carts/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/admin/login,/admin/logout,/users/**,/addresses/**
dubbo:
  application:
    name: dubbo-user-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos
security:
  ignore:
    whitelist:
      - /admin/login