server:
  port: 8003 # 内嵌的 Tomcat 端口号。默认值为 8080。
spring:
  application:
    name: training-service # 微服务名称。
ptoj:
  mysql:
    name: ${MYSQL_DATABASE_NAME:ptoj-user}
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    password: ${MYSQL_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
  nacos:
    host: ${NACOS_HOST:localhost}
    port: ${NACOS_PORT:8848}
    username: ${NACOS_USERNAME:nacos}
    password: ${NACOS_PASSWORD:nacos}

  swagger:
    title: "题单管理接口文档"
    package: love.pangteen.training.controller