version: "3"
services:
  ptoj-redis:
    image: redis:7.2
    container_name: ptoj-redis
    restart: always
    volumes:
      - ${PTOJ_DATA_DIRECTORY}/data/redis/data:/data
    networks:
      ptoj-network:
        ipv4_address: ${REDIS_HOST:-172.21.0.2}
    ports:
      - ${REDIS_PORT:-6379}:6379
    # --requirepass 后面为redis访问密码
    command: redis-server --requirepass ${REDIS_PASSWORD:-123456} --appendonly yes

  ptoj-mysql:
    #    image: mysql:8.2.0
    build: src/mysql
    container_name: ptoj-mysql
    restart: always
    volumes:
      - ${PTOJ_DIRECTORY}/data/mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456} # mysql数据库root账号的密码
      - NACOS_USERNAME=${NACOS_USERNAME:-root} # 后续nacos所用管理员账号
      - NACOS_PASSWORD=${NACOS_PASSWORD:-123456} # 后续nacos所用管理员密码
    ports:
      - ${MYSQL_PUBLIC_PORT:-3306}:3306
    networks:
      ptoj-network:
        ipv4_address: ${MYSQL_HOST:-172.21.0.3}

  ptoj-nacos:
    image: nacos/nacos-server:v2.3.0-slim
#    image: nacos/nacos-server:v2.1.0-slim
    container_name: ptoj-nacos
    restart: always
    depends_on:
      - ptoj-mysql
    environment:
      - JVM_XMX=384m
      - JVM_XMS=384m
      - JVM_XMN=192m
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=${MYSQL_HOST:-172.21.0.3}
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456} # 与上面数据库密码一致
      - MYSQL_SERVICE_DB_NAME=nacos
      - NACOS_AUTH_ENABLE=true # 开启鉴权
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - NACOS_AUTH_TOKEN=PangTeen012345678901234567890123456789012345678901234567890123456789
    ports:
      - ${NACOS_PORT:-8848}:8848
      - 9848:9848
      - 9849:9849
#    healthcheck:
#      test: curl -f http://${NACOS_HOST:-172.21.0.4}:8848/nacos/index.html || exit 1
#      interval: 6s
#      timeout: 10s
#      retries: 10
    networks:
      ptoj-network:
        ipv4_address: ${NACOS_HOST:-172.21.0.4}

#  hoj-frontend:
##    image: registry.cn-shenzhen.aliyuncs.com/hcode/hoj_frontend
#    build: src/frontend
#    container_name: ptoj-frontend
#    restart: always
#    # 开启https，请提供证书
#    #volumes:
#    #  - ./server.crt:/etc/nginx/etc/crt/server.crt
#    #  - ./server.key:/etc/nginx/etc/crt/server.key
#    # 修改前端logo
#    #  - ./logo.a0924d7d.png:/usr/share/nginx/html/assets/img/logo.a0924d7d.png
#    #  - ./backstage.8bce8c6e.png:/usr/share/nginx/html/assets/img/backstage.8bce8c6e.png
#    environment:
#      - SERVER_NAME=localhost # 域名(例如baidu.com)或localhost(本地)
#      - BACKEND_SERVER_HOST=${BACKEND_HOST:-172.20.0.5} # backend后端服务地址
#      - BACKEND_SERVER_PORT=${BACKEND_PORT:-6688} # backend后端服务端口号
#      - USE_HTTPS=false # 使用https请设置为true
#    ports:
#      - "80:80"
#      - "443:443"
#    networks:
#      ptoj-network:
#        ipv4_address: 172.21.0.6

networks:
  ptoj-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET:-172.21.0.0/16}
          gateway: 172.21.0.1