version: "3"
services:
  ptoj-redis:
    image: redis:7.2
    container_name: ptoj-redis
    restart: unless-stopped
    volumes:
      - ${PTOJ_DATA_DIRECTORY}/data/redis/data:/data
    networks:
      ptoj-network:
        ipv4_address: ${REDIS_HOST:-172.21.0.2}
    ports:
      - ${REDIS_PORT:-6379}:6379
    # --requirepass 后面为redis访问密码
    command: redis-server --requirepass ${REDIS_PASSWORD:-123456} --appendonly yes

  ptoj-mysql:
    build: src/mysql
    container_name: ptoj-mysql
    restart: unless-stopped
    volumes:
      - ${PTOJ_DIRECTORY}/data/mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-123456} # mysql数据库root账号的密码
      - NACOS_USERNAME=${NACOS_USERNAME:-root} # 后续nacos所用管理员账号
      - NACOS_PASSWORD=${NACOS_PASSWORD:-123456} # 后续nacos所用管理员密码
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      ptoj-network:
        ipv4_address: ${MYSQL_HOST:-172.21.0.3}

  ptoj-nacos:
    image: nacos/nacos-server:v2.3.0-slim
    container_name: ptoj-nacos
    restart: unless-stopped
    depends_on:
      - ptoj-mysql
    environment:
      - JVM_XMX=256m
      - JVM_XMS=256m
      - JVM_XMN=128m
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=${MYSQL_HOST:-172.21.0.3}
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${MYSQL_PASSWORD:-123456} # 与上面数据库密码一致
      - MYSQL_SERVICE_DB_NAME=nacos
      - NACOS_AUTH_ENABLE=true # 开启鉴权
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_USERNAME:-nacos}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_PASSWORD:-nacos}
      - NACOS_AUTH_TOKEN=PangTeen012345678901234567890123456789012345678901234567890123456789
    ports:
      - ${NACOS_PORT:-8848}:8848
      - "9848:9848"
      - "9849:9849"
    networks:
      ptoj-network:
        ipv4_address: ${NACOS_HOST:-172.21.0.4}

  ptoj-sentinel:
    build: src/sentinel
    container_name: ptoj-sentinel
    restart: unless-stopped
    environment:
      JAVA_OPTS: -Dsentinel.dashboard.auth.username=${SENTINEL_USERNAME:-sentinel} -Dsentinel.dashboard.auth.password=${SENTINEL_PASSWORD:-123456}
    ports:
      - ${SENTINEL_PORT:-8858}:8858
      - "8719:8719"
    networks:
      ptoj-network:
        ipv4_address: ${SENTINEL_HOST:-172.21.0.5}

  ptoj-rocketmq-namesrv:
    image: apache/rocketmq:5.2.0
    container_name: ptoj-rocketmq-namesrv
    command: sh mqnamesrv
    restart: unless-stopped
    #    network_mode: host
    volumes:
      - ${PTOJ_DIRECTORY}/data/rocketmq/namesrv/logs:/home/rocketmq/logs/rocketmqlogs
    environment:
      JAVA_OPT: -server -Xms512m -Xmx512m
    ports:
      - "9876:9876"
    networks:
      ptoj-network:
        ipv4_address: ${ROCKETMQ_SERVER_HOST:-172.21.0.10}

  ptoj-rocketmq-broker:
    image: apache/rocketmq:5.2.0
    container_name: ptoj-rocketmq-broker
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.2.0/conf/broker.conf
    restart: unless-stopped
    #    network_mode: host
    depends_on:
      - ptoj-rocketmq-namesrv
    volumes:
      - ${PTOJ_DIRECTORY}/data/rocketmq/broker/conf/broker.conf:/home/rocketmq/rocketmq-5.2.0/conf/broker.conf
      - ${PTOJ_DIRECTORY}/data/rocketmq/broker/logs:/home/rocketmq/logs/rocketmqlogs
      - ${PTOJ_DIRECTORY}/data/rocketmq/broker/store:/home/rocketmq/store
    environment:
      NAMESRV_ADDR: ptoj-rocketmq-namesrv:9876
      JAVA_OPT_EXT: -server -Xms512M -Xmx512M -Xmn256m
    ports:
      - "10911:10911"
      - "10909:10909"
      - "10912:10912"
    networks:
      ptoj-network:
        ipv4_address: ${ROCKETMQ_BROKER_HOST:-172.21.0.11}

  ptoj-mqconsole:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: ptoj-mqconsole
    restart: unless-stopped
    #    network_mode: host
    depends_on:
      - ptoj-rocketmq-namesrv
    environment:
      JAVA_OPTS: -Dserver.port=19876 -Drocketmq.namesrv.addr=ptoj-rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    ports:
      - "19876:19876"
    networks:
      ptoj-network:
        ipv4_address: ${ROCKETMQ_CONSOLE_HOST:-172.21.0.12}

  ptoj-frontend:
    build: src/frontend
    container_name: ptoj-frontend
    restart: unless-stopped
    volumes:
      - ${PTOJ_DIRECTORY}/data/frontend/crt:/etc/nginx/etc/crt
      - ${PTOJ_DIRECTORY}/data/frontend/html:/usr/share/nginx/html
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost} # 域名(例如baidu.com)或localhost(本地)
      - SERVER_HOST=${GATEWAY_HOST:-172.21.0.20} # backend后端服务地址
      - SERVER_PORT=6688 # backend后端服务端口号
      - USE_HTTPS=${USE_HTTPS:-false} # 使用https请设置为true
    ports:
      - "80:80"
      - "443:443"
    networks:
      ptoj-network:
        ipv4_address: ${FRONTEND_HOST:-172.21.0.9}

  ptoj-gateway:
    image: ptoj-gateway:1.0-SNAPSHOT
    container_name: ptoj-gateway
    restart: unless-stopped
    depends_on:
      - ptoj-mysql
      - ptoj-nacos
      - ptoj-redis
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.21.0.2}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - NACOS_HOST=${NACOS_HOST:-172.21.0.4}
      - NACOS_PORT=${NACOS_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - SENTINEL_HOST=${SENTINEL_HOST:-localhost}
      - SENTINEL_PORT=${SENTINEL_PORT:-8858}
    ports:
      - "6688:6688"
    networks:
      ptoj-network:
        ipv4_address: ${GATEWAY_HOST:-172.21.0.20}


  ptoj-user-service:
    image: user-service:1.0-SNAPSHOT
    container_name: user-service
    restart: unless-stopped
    depends_on:
      - ptoj-mysql
      - ptoj-nacos
      - ptoj-redis
      - ptoj-rocketmq-namesrv
      - ptoj-rocketmq-broker
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.21.0.2}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MYSQL_HOST=${MYSQL_HOST:-172.21.0.3}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_USER:-ptoj-user}
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-123456}
      - NACOS_HOST=${NACOS_HOST:-172.21.0.4}
      - NACOS_PORT=${NACOS_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - ROCKETMQ_HOST=${ROCKETMQ_SERVER_HOST:-172.21.0.4}
      - ROCKETMQ_PORT=${ROCKETMQ_SERVER_PORT:-9876}
      - ROCKETMQ_GROUP=${ROCKETMQ_GROUP:-ptoj}
    ports:
      - "8000:8000"
    networks:
      ptoj-network:
        ipv4_address: ${USER_SERVICE_HOST:-172.21.0.21}

  ptoj-problem-service:
    image: problem-service:1.0-SNAPSHOT
    container_name: problem-service
    restart: unless-stopped
    depends_on:
      - ptoj-mysql
      - ptoj-nacos
      - ptoj-redis
      - ptoj-gateway
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.21.0.2}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MYSQL_HOST=${MYSQL_HOST:-172.21.0.3}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_PROBLEM:-ptoj-problem}
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-123456}
      - NACOS_HOST=${NACOS_HOST:-172.21.0.4}
      - NACOS_PORT=${NACOS_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - ROCKETMQ_HOST=${ROCKETMQ_SERVER_HOST:-172.21.0.4}
      - ROCKETMQ_PORT=${ROCKETMQ_SERVER_PORT:-9876}
      - ROCKETMQ_GROUP=${ROCKETMQ_GROUP:-ptoj}
    ports:
      - "8001:8001"
    networks:
      ptoj-network:
        ipv4_address: ${PROBLEM_SERVICE_HOST:-172.21.0.22}


#  ptoj-training-service:
#    image: training-service:latest
#    container_name: training-service
#    restart: unless-stopped
#    depends_on:
#      - ptoj-mysql
#      - ptoj-nacos
#      - ptoj-redis
#      - ptoj-gateway
#      - ptoj-problem-service
#    environment:
#      - REDIS_HOST=${REDIS_HOST:-172.21.0.2}
#      - REDIS_PORT=${REDIS_PORT:-6379}
#      - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
#      - MYSQL_HOST=${MYSQL_HOST:-172.21.0.3}
#      - MYSQL_PORT=${MYSQL_PORT:-3306}
#      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_TRAINING:-ptoj-training}
#      - MYSQL_USERNAME=root
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-123456}
#      - NACOS_HOST=${NACOS_HOST:-172.21.0.4}
#      - NACOS_PORT=${NACOS_PORT:-8848}
#      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
#      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
#    ports:
#      - "8003:8003"
#    networks:
#      ptoj-network:
#        ipv4_address: ${TRAINING_SERVICE_HOST:-172.21.0.24}

  ptoj-judge-server:
    image: judge-service:latest
    container_name: judge-server-1
    privileged: true
    restart: unless-stopped
    depends_on:
      - ptoj-mysql
      - ptoj-nacos
      - ptoj-redis
      - ptoj-gateway
      - ptoj-problem-service
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.21.0.2}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - MYSQL_HOST=${MYSQL_HOST:-172.21.0.3}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_PROBLEM:-ptoj-problem}
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-123456}
      - NACOS_HOST=${NACOS_HOST:-172.21.0.4}
      - NACOS_PORT=${NACOS_PORT:-8848}
      - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
      - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
      - ROCKETMQ_HOST=${ROCKETMQ_SERVER_HOST:-172.21.0.4}
      - ROCKETMQ_PORT=${ROCKETMQ_SERVER_PORT:-9876}
      - ROCKETMQ_GROUP=${ROCKETMQ_GROUP:-ptoj}
      - JUDGE_SERVER_NAME=${JUDGE_SERVER_1_NAME:-ptoj-judger-1}
      - MAX_TASK_NUM=${MAX_TASK_NUM:-1}
    ports:
      - "8010:8010"
    networks:
      ptoj-network:
        ipv4_address: ${JUDGE_SERVER_1_HOST:-172.21.0.30}

  ptoj-judge:
    #    image: criyle/go-judge
    build: src/judge
    privileged: true
    volumes:
      - ${PTOJ_DIRECTORY}/data/judge/testcase:/judge/test_case
      - ${PTOJ_DIRECTORY}/data/judge/log:/judge/log
      - ${PTOJ_DIRECTORY}/data/judge/run:/judge/run
      - ${PTOJ_DIRECTORY}/data/judge/spj:/judge/spj
    environment:
      - shm-size=256m
    ports:
      - "5050:5050"
    networks:
      ptoj-network:
        ipv4_address: ${JUDGE_HOST:-172.21.0.6}

#  ptoj-es:
#    image: elasticsearch:7.14.0
#    container_name: ptoj-es
#    restart: unless-stopped
#    volumes:
#      - ${PTOJ_DIRECTORY}/data/elasticsearch/data:/usr/share/elasticsearch/data
#      - ${PTOJ_DIRECTORY}/data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
#    environment:
#      - cluster.name=elasticsearch
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      ptoj-network:
#        ipv4_address: ${ES:-172.21.0.6}

    #  ptoj-mq:
    #    image: rabbitmq:3.12.12-management
    #    container_name: ptoj-mq
    #    hostname: ptoj-mq
    #    restart: unless-stopped
    #    volumes:
    ##      - ${PTOJ_DIRECTORY}/data/rabbitmq/plugins:/plugins
    #      - ${PTOJ_DIRECTORY}/data/rabbitmq/data:/var/lib/rabbitmq
    #    environment:
    #      - RABBITMQ_DEFAULT_USER=root
    #      - RABBITMQ_DEFAULT_PASS=123456
    #    ports:
    #      - "15672:15672"
    #      - "5672:5672"
    #    networks:
    #      ptoj-network:
    #        ipv4_address: ${MQ_HOST:-172.21.0.5}

networks:
  ptoj-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET:-172.21.0.0/16}
          gateway: 172.21.0.1