server:
  port: 8003 # 内嵌的 Tomcat 端口号。默认值为 8080。
spring:
  application:
    name: judge-service # 微服务名称。
ptoj:
  mysql:
    name: ptoj-judge
    host: localhost
    port: 3306
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
  nacos:
    host: localhost
    port: 8848
    username: nacos
    password: nacos
#  rabbitmq:
#    host: localhost
#    port: 5672
#    namespace: /ptoj
#    username: root
#    password: 123456
  rocketmq:
    host: localhost
    port: 9876
    group: ptoj
  swagger:
    title: "评测管理接口文档"
    package: love.pangteen.judge.controller

ptoj-judge-server:
    max-task-num: ${MAX_TASK_NUM:-1} # -1表示最大并行任务数为cpu核心数+1
    name: ${JUDGE_SERVER_NAME:ptoj-judger-1} # 判题机名字 唯一不可重复！！！