server:
  port: 8000 # 内嵌的 Tomcat 端口号。默认值为 8080。
spring:
  application:
    name: user-service # 微服务名称。
ptoj:
  mysql:
    name: ptoj-user
    host: localhost
    port: 3306
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
  nacos:
    host: localhost
    port: 8848
    username: nacos
    password: nacos
  rocketmq:
    host: localhost
    port: 9876
    group: ptoj
  swagger:
    title: "用户管理接口文档"
    package: love.pangteen.user.controller
logging:
  level:
    root: info