server:
  port: 6688 # 内嵌的 Tomcat 端口号。默认值为 8080。
spring:
  application:
    name: user-service # 微服务名称。
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${ptoj.mysql.host}:${ptoj.mysql.port}/${ptoj.mysql.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${ptoj.mysql.password}
  redis:
    host: ${ptoj.redis.host}
    port: ${ptoj.redis.port}
    timeout: 60000
    jedis:
      pool:
        min-idle: 10 #连接池中的最小空闲连接
        max-idle: 50 #连接池中的最大空闲连接
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
    password: ${ptoj.redis.password}

knife4j:
  enable: true
  openapi:
    title: PTOJ接口文档
    description: "PTOJ接口文档"
    email: 1687289734@qq.com
    concat: PangTeen
    url: https://pangteen.love
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - love.pangteen.user.controller